#!/bin/bash

echo "Running pre-commit hook..."

if ! command -v golangci-lint &> /dev/null
then
    echo "golangci-lint could not be found. Please install it to use this pre-commit hook."
    exit 1
fi

changed_files=$(git diff --cached --name-only --diff-filter=ACMRT | grep '\.go$')

if [ -n "$changed_files" ]; then
    golangci-lint run --files "$changed_files"
    if [ $? -ne 0 ]; then
        echo "golangci-lint found issues in the modified Go files. Please fix them before committing."
        exit 1
    fi
else
    echo "No Go files changed. Skipping golangci-lint."
fi

echo "Pre-commit hook completed successfully."
exit 0