version: "3"

services:
  python-app:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: python-app
    tty: true
    stdin_open: true

  kotlin-app:
    build:
      context: ./kotlin
      dockerfile: Dockerfile
    container_name: kotlin-app
    tty: true
    stdin_open: true
